### ISSUE TITLE
Heb je volodend ecommits hier?

### ISSUE THREAD

**Issue by Theo-denBlanken** [eniciodehaas/WPthema#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/eniciodehaas/WPthema/blob/master/

Feedback: Het thema lijkt verder dan de bestanden laten zien[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by eniciodehaas** [comment]
Ik heb het wp thema afgerond tot het submenu en de files gecommit op github
